### ISSUE TITLE
error during deployment 

### ISSUE THREAD

**Issue by xiasiliang-hit** [msgbyte/tailchat#145]
I get this error 

  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2607, in requires
    dm = self._dep_map
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _dep_map

when I deploy using 
docker-compose  -f docker-compose.devops.yml up -d

following  https://tailchat.msgbyte.com/zh-Hans/blog/2023/03/27/deploy-in-synology

my env is 
centOS on tencent cloud, python 3.6

**Comment by moonrailgun** [comment]
Its looks like your environment is incorrect.

Did your nas support python?
Did you install `docker` + `docker-compose` environment correct?

you can try to run a simple docker-compose config to test it. Like follow config:

```yml
version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
      - 443:443
```
